# MOD_SLUG
# MOD_GAME_DIR
# MOD_ARCHIVES
# MOD_ARCHIVE_XLS

set(MOD_GAME_DIR_ARCHIVE_DIR "${MOD_GAME_DIR}/archive/pc/mod")
set(MOD_GAME_DIR_ARCHIVE_XL_DIR "${MOD_GAME_DIR}/archive/pc/mod")

set(MOD_GAME_DIR_ARCHIVES)
set(MOD_GAME_DIR_ARCHIVE_XLS)

foreach(ARCHIVE ${MOD_ARCHIVES})
  get_filename_component(ARCHIVE_NAME ${ARCHIVE} NAME)
  list(APPEND MOD_GAME_DIR_ARCHIVES "${MOD_GAME_DIR_ARCHIVE_DIR}/${ARCHIVE_NAME}")
  add_custom_command(
    OUTPUT ${MOD_GAME_DIR_ARCHIVE_DIR}/${ARCHIVE_NAME}
    DEPENDS ${ARCHIVE}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
    ${ARCHIVE}
    ${MOD_GAME_DIR_ARCHIVE_DIR}/${ARCHIVE_NAME}
  )
endforeach()

foreach(ARCHIVE_XL ${MOD_ARCHIVE_XLS})
  get_filename_component(ARCHIVE_XL_NAME ${ARCHIVE_XL} NAME)
  list(APPEND MOD_GAME_DIR_ARCHIVES "${MOD_GAME_DIR_ARCHIVE_XLS}/${ARCHIVE_XL_NAME}")
  add_custom_command(
    OUTPUT ${MOD_GAME_DIR_ARCHIVE_XLS}/${ARCHIVE_XL_NAME}
    DEPENDS ${ARCHIVE_XL}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
    ${ARCHIVE}
    ${MOD_GAME_DIR_ARCHIVE_XLS}/${ARCHIVE_XL_NAME}
  )
endforeach()

add_custom_target(${MOD_SLUG}_archives
  DEPENDS ${MOD_GAME_DIR_ARCHIVES} ${MOD_GAME_DIR_ARCHIVE_XLS}
)
set_target_properties(${MOD_SLUG}_archives PROPERTIES FOLDER "Archives")
add_dependencies(${MOD_SLUG} ${MOD_SLUG}_archives)