# CMAKE_REDSCRIPT_CREATE_SHARED_LIBRARY
# CMAKE_REDSCRIPT_CREATE_SHARED_MODULE
# CMAKE_REDSCRIPT_CREATE_STATIC_LIBRARY
# CMAKE_REDSCRIPT_COMPILE_OBJECT
# CMAKE_REDSCRIPT_LINK_EXECUTABLE

set(CMAKE_BUILD_TYPE_INIT Debug)

set(CMAKE_Redscript_COMPILE_OBJECT "\"${CMAKE_COMMAND}\" -E copy <SOURCE> <OBJECT>")

set(CMAKE_Redscript_LINK_EXECUTABLE "<CMAKE_Redscript_COMPILER> <OBJECTS> -o <TARGET>")