if(NOT TARGET RedLib)
  if(NOT ${CMAKE_CURRENT_SOURCE_DIR}/deps/red_lib/CMakeLists.txt)
    find_package(Git QUIET)
    if(GIT_FOUND)
      message(STATUS "Cloning RedLib into ${CMAKE_CURRENT_SOURCE_DIR}/deps/red_lib")
      execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init deps/red_lib WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    else()
      message(FATAL_ERROR "Could not find git")
    endif()
  endif()
  add_compile_definitions(NOMINMAX)
  add_subdirectory(deps/red_lib)
endif()