macro(resolve_dependency PATH)
  if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${PATH}/CMakeLists.txt)
    find_package(Git QUIET)
    if(GIT_FOUND)
      message(STATUS "Cloning ${PATH} into ${CMAKE_CURRENT_SOURCE_DIR}/${PATH}")
      execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init ${PATH} WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    else()
      message(FATAL_ERROR "Could not find git")
    endif()
  endif()
endmacro()