# MOD_TWEAKS_SOURCE_DIR
# MOD_GAME_DIR
# MOD_SLUG

set(MOD_GAME_DIR_TWEAKS_FILE "${MOD_GAME_DIR}/r6/tweaks/${MOD_SLUG}.yaml")

file(GLOB_RECURSE MOD_TWEAKS_SOURCE_FILES "${MOD_TWEAKS_SOURCE_DIR}/*.yaml")

add_custom_command(
  OUTPUT ${MOD_GAME_DIR_TWEAKS_FILE}
  DEPENDS ${MOD_TWEAKS_SOURCE_FILES}
  COMMAND ${CMAKE_COMMAND} -D COMMENT_SLUG="\#" -D GLOB_EXT="yaml" -D HEADER_FILE="${CMAKE_CURRENT_LIST_DIR}/Header.txt" -D PACKED_FILE=${MOD_GAME_DIR_TWEAKS_FILE} -D SEARCH_FOLDER=${MOD_TWEAKS_SOURCE_DIR} -P ${CMAKE_CURRENT_LIST_DIR}/PackFiles.cmake
)

add_custom_target(tweaks
  DEPENDS ${MOD_GAME_DIR_TWEAKS_FILE}
)