macro(configure_folder_file FILENAME)
    if(EXISTS ${MOD_SOURCE_DIR}/${FILENAME})
        message(STATUS "Configuring ${MOD_SOURCE_DIR}/${FILENAME}")
    else()
    message(STATUS "Configuring ${MOD_SOURCE_DIR}/${FILENAME} - Warning: file does not exist")
    endif()
    foreach(FOLDER ${${MOD_SLUG}_GAME_DIR_FOLDERS})
        configure_file(${MOD_SOURCE_DIR}/${FILENAME} ${FOLDER}/${FILENAME} COPYONLY)
        list(APPEND ${MOD_SLUG}_GAME_DIR_FILES ${FOLDER}/${FILENAME})
    endforeach()
endmacro()