# MOD_GAME_DIR
# CYBERPUNK_2077_GAME_DIR
macro(configure_install)
file(GLOB MOD_GAME_DIR_INSTALL_FILES ${MOD_GAME_DIR}/*)

install(DIRECTORY ${MOD_GAME_DIR_INSTALL_FILES}
  DESTINATION ${CYBERPUNK_2077_GAME_DIR})
endmacro()